# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels:
      - 'dependencies'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@grafana/runtime'
        update-types: ['version-update: semver-patch']
      - dependency-name: '@grafana/data'
        update-types: ['version-update: semver-patch']
      - dependency-name: '@grafana/ui'
        update-types: ['version-update: semver-patch']
      - dependency-name: '@grafana/toolkit'
        update-types: ['version-update: semver-patch']
