name: Validate Policy Bot Config

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate:
    name: Validate policy bot config
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Validate policy bot config
        run: |
          curl \
            --silent \
            --fail-with-body \
            --request PUT \
            --upload-file .policy.yml \
            https://github-policy-bot.grafana-ops.net/api/validate
