name: Validate Plugin Build (Compat, Lint, Typecheck and Test)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  set-up:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Latest Grafana API compatibility check
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data,@grafana/runtime,@grafana/scenes,@grafana/schema,@grafana/ui

      - name: Lint
        run: yarn lint

      - name: Build plugin and typecheck
        run: yarn build --json=artifacts/currentBundleSize.json --no-devtool

      - name: Integration and unit tests
        run: yarn test

      - name: Upload this build's bundle size artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: currentBundleSize
          path: ./artifacts/currentBundleSize.json
          overwrite: true
