export enum DataTestIds {
  PRIVATE_PROBES_LIST = 'private-probes-list',
  PUBLIC_PROBES_LIST = 'public-probes-list',
  CHECK_FORM_HTTP_VALIDATION_REGEX = 'check-form-http-validation-regex',
  CHOOSE_CHECK_TYPE = 'choose-check-type',
  CHECK_GROUP_CARD = 'check-group-card',
  INDIVIDUAL_ASSERTION = 'individual-assertion',
  REQUEST_ASSERTION = 'request-assertion',
  MULTI_HTTP_REQUEST = 'multihttp-request',
  ACTIONS_BAR = 'actions-bar',
  PAGE_READY = 'page-ready',
  PAGE_NOT_READY = 'page-not-ready',
  PROBE_USAGE_LINK = 'probe-usage-link',
  TEST_ROUTER_INFO = 'test-router-info',
  TEST_ROUTER_INFO_PATHNAME = 'test-router-info-pathname',
  TEST_ROUTER_INFO_SEARCH = 'test-router-info-search',
  CHECK_FORM_SUBMIT_BUTTON = 'check-form-submit-button',
  CONFIRM_UNSAVED_MODAL_HEADING = 'confirm-unsaved-modal-heading',
}
