approvedGitRepositories:
  - "https://github.com/grafana/*"
  - "ssh://git@github.com/grafana/*"
  - "git@github.com:grafana/*"

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 4320

yarnPath: .yarn/releases/yarn-4.15.0.cjs
