approvedGitRepositories:
  - "https://github.com/grafana/*"
  - "ssh://git@github.com/grafana/*"
  - "git@github.com:grafana/*"

enableScripts: false

npmScopes:
  grafana-cloud:
    npmRegistryServer: 'https://us-npm.pkg.dev/grafanalabs-dev/cloud-npm-dev/'

nodeLinker: node-modules

npmMinimalAgeGate: 4320

yarnPath: .yarn/releases/yarn-4.15.0.cjs
