# The following are pulled from env variables
'project_id_env': CROWDIN_PROJECT_ID
'api_token_env': CROWDIN_PERSONAL_TOKEN

'base_path': '../'
'base_url': 'https://grafana.api.crowdin.com'
'preserve_hierarchy': true

files:
  [
    {
      'source': '/src/locales/en-US/{{PLUGIN_ID}}.json',
      'translation': '/src/locales/%locale%/%original_file_name%',
    },
  ]
