/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/i18n-tooling`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.github.io/plugin-tools/docs/advanced-configuration#extending-the-webpack-config
 */

import React from 'react';
import { i18n } from '@grafana/runtime';

import pluginJson from '../../plugin.json';

const I18N_NAMESPACE = pluginJson.id;

export const Trans: typeof i18n.Trans = (props) => {
  return (
    <i18n.Trans i18nKey={props.i18nKey} ns={I18N_NAMESPACE}>
      {props.children}
    </i18n.Trans>
  );
};

export const t: typeof i18n.t = (id: string, defaultMessage: string, values?: Record<string, unknown>) => {
  return i18n.t(`${I18N_NAMESPACE}:${id}`, defaultMessage, values);
};
