name: Setup Plugin Environment (repo / node)
description: Setups up a Node.js environment
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "22"
        cache: 'yarn'

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock', 'package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Get yarn cache directory path
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Yarn Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install --immutable --prefer-offline
      shell: bash
