#!/bin/bash

fail() {
  echo error: "$@" 1>&2
  exit 1
}


gcom() {
  url="https://grafana.com/api${1}"
  shift
  ret=$(curl -s -H "Authorization: Bearer ${GCOM_TOKEN}" "$url" "$@")
  if [ "$ret" = "true" ]; then
    echo true
    return
  fi
  if echo "$ret" | jq -e .code > /dev/null; then
    code=$(echo "$ret" | jq -r .code)
    msg=$(echo "$ret" | jq -r .message)
    fail "${code}: ${msg}"
  else
    echo "$ret"
  fi
}

GIT_TAG=$(git tag --points-at HEAD)
VERSION="${GIT_TAG//v}"
PLUGIN_URL='https://github.com/grafana/synthetic-monitoring-app/releases/download/'"$GIT_TAG"'/grafana-synthetic-monitoring-app-'"${VERSION}"'.zip'
MD5URL='https://github.com/grafana/synthetic-monitoring-app/releases/download/'"$GIT_TAG"'/info.json'
PLUGIN_NAME='grafana-synthetic-monitoring-app'

# Get a package hash for publishing to g-com from published github assets
PKG_SUM=$(curl -L -H "Accept: application/json" $MD5URL | jq -r .plugin.md5)

# Publish version to gcom plugin listings
gcom /plugins \
  -d "download[any][url]=$PLUGIN_URL" \
  -d "download[any][md5]=$PKG_SUM" \
  -d url=https://github.com/grafana/synthetic-monitoring-app