{
 "title": "Synthetic Monitoring Summary",
 "tags": [ "synthetic-monitoring" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "check_type",
    "label": "Check Type",
    "query": {
     "query": "label_values(sm_check_info, check_name)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(sm_check_info, region)"
    }
   },
   { "name": "_DS_SM_LOGS", "query": "${DS_SM_LOGS}" }
  ]
 },
 "panels": [
  { "title": "$check_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "check_type" },
  {
   "title": "$check_type error rate",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (\n  sum by (probe, geohash)\n (\n (\n rate(probe_all_success_sum[$__range])\n OR\n rate(probe_success_sum[$__range])\n)\n *\n on (instance, job, probe, config_version)\n group_left(geohash)\n max\n by (instance, job, probe, config_version, check_name, geohash)\n (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})\n) \n / \n sum by (probe, geohash)\n (\n (\n rate(probe_all_success_count[$__range])\n OR\n rate(probe_success_count[$__range])\n)\n *\n on (instance, job, probe, config_version)\n group_left(geohash)\n max\n by (instance, job, probe, config_version, check_name, geohash)\n (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})\n)\n))"
    }
   ]
  },
  {
   "title": "$check_type check error percentage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (  sum( ( rate(probe_all_success_sum[$__range]) OR rate(probe_success_sum[$__range])) * on (instance, job, probe, config_version) group_left(geohash) max by (instance, job, probe, config_version, check_name, geohash) (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})) /  sum( ( rate(probe_all_success_count[$__range]) OR rate(probe_success_count[$__range])) * on (instance, job, probe, config_version) group_left(geohash) max by (instance, job, probe, config_version, check_name, geohash) (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})))",
     "legendFormat": "% Errors"
    }
   ]
  },
  {
   "title": "$check_type checks",
   "type": "table",
   "description": "* **instance**: the instance that corresponds to this check.\n* **job**: the job that corresponds to this check.\n* **reachability**: the percentage of all the checks that have succeeded during the whole time period.\n* **latency**: the average time to receive an answer across all the checks during the whole time period.\n* **state**: whether the target was up or down the last time it was checked.\n* **uptime**: the fraction of time the target was up  during the whole period.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance, job, check_name)\n(\n  (\n    rate(probe_all_success_sum[$__range])\n    OR\n    rate(probe_success_sum[$__range])\n  )\n  *\n  on (instance, job, probe, config_version)\n  group_left(check_name)\n  max\n  by (instance, job, probe, config_version, check_name)\n  (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})\n)\n/\nsum by (instance, check_name, job)\n(\n  (\n    rate(probe_all_success_count[$__range])\n    OR\n    rate(probe_success_count[$__range])\n  )\n  *\n  on (instance, job, probe, config_version)\n  group_left(check_name)\n  max\n  by (instance, job, probe, config_version, check_name)\n  (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})\n)",
     "legendFormat": "{{check_name}}-{{instance}}-uptime"
    },
    {
     "expr": "sum by (instance, job, check_name)\n(\n  (\n    rate(probe_all_duration_seconds_sum[$__range])\n    OR\n    rate(probe_duration_seconds_sum[$__range])\n  )\n  *\n  on (instance, job, probe, config_version)\n  group_left(check_name)\n  max by (instance, job, probe, config_version, check_name)\n  (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})\n)\n/\nsum by (instance, job, check_name)\n(\n  (\n    rate(probe_all_duration_seconds_count[$__range])\n    OR\n    rate(probe_duration_seconds_count[$__range])\n  )\n  *\n  on (instance, job, probe, config_version)\n  group_left(check_name)\n  max by (instance, job, probe, config_version, check_name)\n  (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})\n)",
     "legendFormat": "{{check_name}}-{{instance}}-latency"
    },
    {
     "expr": "ceil(\n  sum by (instance, job, check_name)\n  (\n    (\n      rate(probe_all_success_sum[5m])\n      OR\n      rate(probe_success_sum[5m])\n    )\n    *\n    on (instance, job, probe, config_version)\n    group_left(check_name)\n    max\n    by (instance, job, probe, config_version, check_name)\n    (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})\n  )\n  /\n  sum by (instance, check_name, job)\n  (\n    (\n      rate(probe_all_success_count[5m])\n      OR\n      rate(probe_success_count[5m])\n    )\n    *\n    on (instance, job, probe, config_version)\n    group_left(check_name)\n    max\n    by (instance, job, probe, config_version, check_name)\n    (sm_check_info{check_name=\"$check_type\", region=~\"$region\"})\n  )\n)",
     "legendFormat": "{{check_name}}-{{instance}}-uptime"
    },
    {
     "expr": "sum_over_time(\n  (\n    ceil(\n      sum by (instance, job) (increase(probe_all_success_sum[5m]) * on (instance, job, probe, config_version) sm_check_info{check_name=\"$check_type\"})\n      /\n      sum by (instance, job) (increase(probe_all_success_count[5m]))\n    )\n  )[$__range:]\n)\n/\ncount_over_time(\n  (\n      sum by (instance, job) (increase(probe_all_success_count[5m]))\n  )[$__range:]\n)"
    }
   ]
  },
  {
   "title": "$check_type latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum((rate(probe_all_duration_seconds_sum[5m]) OR rate(probe_duration_seconds_sum[5m])) * on (instance, job, probe, config_version) group_left max(sm_check_info{check_name=\"$check_type\", region=~\"$region\"}) by (instance, job, probe, config_version))  by (job, instance) / sum((rate(probe_all_duration_seconds_count[5m]) OR rate(probe_duration_seconds_count[5m])) * on (instance, job, probe, config_version) group_left max(sm_check_info{check_name=\"$check_type\", region=~\"$region\"}) by (instance, job, probe, config_version)) by (job, instance)",
     "legendFormat": "{{job}}/{{ instance }}"
    }
   ]
  }
 ]
}