{
 "title": "Synthetic Monitoring Traceroute",
 "tags": [ "synthetic-monitoring" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "probe",
    "query": {
     "query": "label_values(sm_check_info{check_name=\"traceroute\"},probe)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(sm_check_info{check_name=\"traceroute\", probe=~\"$probe\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(sm_check_info{check_name=\"traceroute\", job=\"$job\", probe=~\"$probe\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traceroute path",
   "type": "nodeGraph",
   "description": "Shows all the routes a check takes to the destination",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "instance": "$instance", "job": "$job" }
   ]
  },
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Route hash",
   "type": "timeseries",
   "description": "Shows the hashed value of all the hosts traversed in a single traceroute. Can be used to determine the volatility of the routes over time",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "probe_traceroute_route_hash{probe=~\"$probe\", job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{probe}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Most common hosts",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "sum by (Hosts) (count_over_time({check_name=\"traceroute\", job=\"$job\", instance=\"$instance\", probe=~\"$probe\"} | logfmt | Hosts != \"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Slowest hosts",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "(avg_over_time({check_name=\"traceroute\", job=\"$job\", instance=\"$instance\", probe=~\"$probe\"} | logfmt | Hosts != \"\" | unwrap duration_seconds(ElapsedTime) [$__interval]) by (Hosts))"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Overall packet loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "probe_traceroute_packet_loss_percent{instance=\"$instance\", job=\"$job\", probe=~\"$probe\"}",
     "legendFormat": "{{probe}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Average total trace time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(probe_all_duration_seconds_sum{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__range]) OR rate(probe_duration_seconds_sum{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__range]))) / sum((rate(probe_all_duration_seconds_count{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__range]) OR rate(probe_duration_seconds_count{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Average Total Hops",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_traceroute_total_hops{instance=\"$instance\", job=\"$job\", probe=~\"$probe\"}",
     "legendFormat": "{{probe}}",
     "stepMode": "min"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{instance=\"$instance\", job=\"$job\", probe=~\"$probe\", check_name=\"traceroute\"}"
    }
   ]
  }
 ]
}