{
 "title": "worldPing ICMP",
 "tags": [ "worldping" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "probe",
    "query": "label_values(worldping_check_info{check_name=\"ping\"},probe)"
   },
   {
    "name": "instance",
    "query": "label_values(worldping_check_info{check_name=\"ping\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Downtime",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "expr": "100-(100 * avg((sum_over_time(probe_success{instance=\"$instance\"}[$__range]) / count_over_time(probe_success{instance=\"$instance\"}[$__range])) * on (instance, job, probe) group_left(latitude, longitude, geohash) worldping_check_info{check_name=\"ping\", instance=\"$instance\"}) by (probe, latitude, longitude, geohash))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg((sum_over_time(probe_success{probe=~\"$probe\", instance=\"$instance\"}[$__range]) *  on (instance, job, probe, config_version) worldping_check_info{check_name=\"ping\", instance=\"$instance\", probe=~\"$probe\"}) / (count_over_time(probe_success{probe=~\"$probe\", instance=\"$instance\"}[$__range]) *  on (instance, job, probe, config_version) worldping_check_info{check_name=\"ping\", instance=\"$instance\", probe=~\"$probe\"}))"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(topk(1,worldping_check_info{probe=~\"$probe\", instance=\"$instance\", check_name=\"ping\"})) by (frequency)",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Error Rate : $probe ⮕ $endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(sum_over_time(probe_success{probe=~\"$probe\", instance=\"$instance\"}[$__interval]) *  on (instance, job, probe, config_version) worldping_check_info{check_name=\"ping\",instance=\"$instance\", probe=~\"$probe\"}) / (sum(count_over_time(probe_success{probe=~\"$probe\", instance=\"$instance\"}[$__interval]) *  on (instance, job, probe, config_version) worldping_check_info{check_name=\"ping\",instance=\"$instance\", probe=~\"$probe\"}))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Response Latency: $probe ⮕ $endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_icmp_duration_seconds{probe=~\"$probe\", instance=\"$instance\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Probes",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "1 - max((sum_over_time(probe_success{instance=\"$instance\"}[$__range]) / count_over_time(probe_success{instance=\"$instance\"}[$__range])) * on (instance, job, probe) group_left(label_country) worldping_check_info{check_name=\"ping\",instance=\"$instance\"}) by (probe, label_country)",
     "legendFormat": "{{probe}} ({{ label_country }})"
    }
   ]
  },
  {
   "title": "Response Latency by Probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{probe=~\"$probe\", instance=\"$instance\"} * on (instance, job,probe,config_version) group_left worldping_check_info{check_name=\"ping\",probe=~\"$probe\",instance=\"$instance\"}) by (probe)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "logs for $probe: $endpoint",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{probe=~\"$probe\",instance=\"$instance\", probe_success=\"0\"}"
    }
   ]
  }
 ]
}