{
 "title": "worldPing Summary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ping Probe Errors",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(((probe_success * on (check_id, probe) group_left(latitude, longitude, geohash)worldping_check_info{check_name=\"ping\", latitude!=\"0.000000\"} ) -1) * -1) by (probe, latitude, longitude, geohash)"
    }
   ]
  },
  {
   "title": "HTTP Probe Errors",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(((probe_success * on (check_id, probe) group_left(latitude, longitude, geohash)worldping_check_info{check_name=\"http\", latitude!=\"0.000000\"} ) -1) * -1) by (probe, latitude, longitude, geohash)"
    }
   ]
  },
  {
   "title": "Ping Checks",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(1 - (sum_over_time(probe_success[$__range]) / count_over_time(probe_success[$__range])) * on (check_id, probe) group_left(endpoint) worldping_check_info{check_name=\"ping\", latitude!=\"0.000000\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP Checks",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(1 - (sum_over_time(probe_success[$__range]) / count_over_time(probe_success[$__range])) * on (check_id, probe) group_left(endpoint) worldping_check_info{check_name=\"http\", latitude!=\"0.000000\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}