{
 "title": "worldPing HTTP",
 "tags": [ "worldping" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "probe",
    "query": "label_values(worldping_check_info,probe)"
   },
   {
    "name": "endpoint",
    "query": "label_values(worldping_check_info{check_name=\"http\"},endpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Downtime",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "expr": "100-(100 * avg((sum_over_time(probe_success[$__range]) / count_over_time(probe_success[$__range])) * on (check_id, probe) group_left(latitude, longitude, geohash) worldping_check_info{check_name=\"http\", endpoint=~\"$endpoint\", latitude!=\"0.000000\"}) by (probe, latitude, longitude, geohash))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg((sum_over_time(probe_success{probe=~\"$probe\"}[$__range]) *  on (check_id, probe, config_version) worldping_check_info{endpoint=\"$endpoint\",probe=~\"$probe\"}) / (count_over_time(probe_success{probe=~\"$probe\"}[$__range]) *  on (check_id, probe, config_version) worldping_check_info{endpoint=\"$endpoint\", probe=~\"$probe\"}))"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(topk(1,worldping_check_info{probe=~\"$probe\",endpoint=\"$endpoint\"})) by (frequency)",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min((probe_ssl_earliest_cert_expiry{probe=~\"$probe\"} *  on (check_id, probe, config_version) worldping_check_info{endpoint=\"$endpoint\",probe=~\"$probe\"})) - time()"
    }
   ]
  },
  {
   "title": "Error Rate : $probe ⮕ $endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(sum_over_time(probe_success{probe=~\"$probe\"}[$__interval]) *  on (check_id, probe, config_version) worldping_check_info{check_name=\"http\", endpoint=\"$endpoint\", probe=~\"$probe\"}) / (sum(count_over_time(probe_success{probe=~\"$probe\"}[$__interval]) *  on (check_id, probe, config_version) worldping_check_info{check_name=\"http\", endpoint=\"$endpoint\", probe=~\"$probe\"}))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Response Latency: $probe ⮕ $endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_http_duration_seconds{probe=~\"$probe\"} * on (check_id,probe,config_version) group_left worldping_check_info{check_name=\"http\",probe=~\"$probe\",endpoint=\"$endpoint\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Probes",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "1 - max((sum_over_time(probe_success[$__range]) / count_over_time(probe_success[$__range])) * on (check_id,probe)  group_left(label_country) worldping_check_info{check_name=\"http\",endpoint=\"$endpoint\"}) by (probe, label_country)",
     "legendFormat": "{{probe}} ({{label_country}})"
    }
   ]
  },
  {
   "title": "Response Latency by Probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{probe=~\"$probe\"} * on (check_id,probe,config_version) group_left worldping_check_info{check_name=\"http\",probe=~\"$probe\",endpoint=\"$endpoint\"}) by (probe)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "logs for $probe: $endpoint",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{probe=~\"$probe\",endpoint=\"$endpoint\", probe_success=\"0\"}"
    }
   ]
  }
 ]
}