{
 "title": "worldPing DNS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "probe",
    "query": "label_values(worldping_check_info{check_name=\"dns\"},probe)"
   },
   {
    "name": "job",
    "query": "label_values(worldping_check_info{check_name=\"dns\", probe=~\"$probe\"},job)"
   },
   {
    "name": "instance",
    "query": "label_values(worldping_check_info{check_name=\"dns\", job=\"$job\", probe=~\"$probe\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Downtime",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "expr": "100*(1 - (sum(rate(probe_success_sum{instance=\"$instance\", job=\"$job\"}[$__range]) *  on (instance, job, probe, config_version) group_left(geohash) worldping_check_info{check_name=\"dns\", instance=\"$instance\", job=\"$job\"}) by (probe, geohash)/ sum(rate(probe_success_count{instance=\"$instance\", job=\"$job\"}[$__range]) *  on (instance, job, probe, config_version) group_left(geohash) worldping_check_info{check_name=\"dns\", instance=\"$instance\", job=\"$job\"}) by (probe, geohash)))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(probe_success_sum{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__range])) / sum(rate(probe_success_count{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(probe_dns_lookup_time_seconds_sum{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__range])) / sum(rate(probe_dns_lookup_time_seconds_count{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Answer Records",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_answer_rrs{probe=~\"$probe\",instance=\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(topk(1,worldping_check_info{probe=~\"$probe\", instance=\"$instance\", check_name=\"dns\"})) by (frequency)",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Error Rate : $probe ⮕ $job / $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(1-(sum(rate(probe_success_sum{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__interval])) / sum(rate(probe_success_count{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__interval]))))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Response Latency by Probe",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"} * on (instance, job,probe,config_version) group_left probe_success{probe=~\"$probe\",instance=\"$instance\", job=\"$job\"} > 0) by (probe)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Resource Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(probe_dns_answer_rrs{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "Answer Records"
    },
    {
     "expr": "avg(probe_dns_authority_rrs{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "Authority Records"
    },
    {
     "expr": "avg(probe_dns_additional_rrs{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "Additional Records"
    }
   ]
  },
  {
   "title": "Error logs for $probe: $instance",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{probe=~\"$probe\",instance=\"$instance\", job=\"$job\", probe_success=\"0\"}"
    }
   ]
  }
 ]
}