/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/i18n-tooling`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.github.io/plugin-tools/docs/advanced-configuration#extending-the-webpack-config
 */

import React from 'react';
import { i18n } from '@grafana/runtime';

import pluginJson from 'plugin.json';

const I18N_NAMESPACE = pluginJson.id;

// this is so the extract script doesn't recognise them
const RuntimeTrans = i18n.Trans;
const RuntimeT = i18n.t;

export const Trans: typeof i18n.Trans = (props) => {
  return (
    <RuntimeTrans ns={I18N_NAMESPACE} {...props}>
      {props.children}
    </RuntimeTrans>
  );
};

export const t: typeof i18n.t = (id: string, ...args) => {
  return RuntimeT(`${I18N_NAMESPACE}:${id}`, ...args);
};
