name: Setup Plugin Environment and Cache

on:
  workflow_call:

permissions:
  contents: read

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Plugin Environment
        uses: ./.github/actions/setup-env
