name: Publish TechDocs
on:
  workflow_call:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
permissions: {}
jobs:
  publish-docs:
    uses: grafana/shared-workflows/.github/workflows/publish-techdocs.yaml@main
    permissions:
      contents: read
      id-token: write
    with:
      namespace: default
      kind: component
      name: synthetic-monitoring-app
      default-working-directory: .
