name: DangerJS Checks

on:
  pull_request:
    branches:
      - feat/webpack-bundle-analyzer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Make artifacts folder
        run: mkdir artifacts

      - name: Build frontend
        run: yarn build --json=artifacts/currentBundleSize.json --no-devtool

      - name: Download mainBundleSize
        uses: dawidd6/action-download-artifact@v7
        with:
          workflow: main-bundle-size.yml
          name: mainBundleSize
          path: artifacts

      - name: DangerJS
        run: yarn danger:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
