name: Crowdin Download Action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download-sources-from-crowdin:
    if: github.repository == 'grafana/synthetic-monitoring-app'
    runs-on: ubuntu-x64
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - name: Get GitHub App token
        id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@46f48da11e78ebdba7a8747ae456b11062fac83e # create-github-app-token/v0.3.1
        with:
          github_app: grafana-pr-automation
      - name: Get vault secrets
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@a53fc80bc30b0a16a262520465db899fa3af08b7 # get-vault-secrets/v1.3.2
        with:
          # Vault secret paths:
          # - ci/repo/grafana/synthetic-monitoring-app/grafana-frontend-crowdin-token
          repo_secrets: |
            CROWDIN_TOKEN=grafana-frontend-crowdin-token:access_token
      - name: Download from Crowdin
        uses: grafana/grafana-github-actions/crowdin-download@26e65a1da9ffdf35d3e8cc6dbeffbccf16022d88 # main
        with:
          crowdin_token: ${{ env.CROWDIN_TOKEN }}
          crowdin_project_id: 64
          github_repo_token: ${{ steps.get-github-app-token.outputs.token }}
