name: i18n - Crowdin Upload Action

on:
  workflow_dispatch:
  push:
    #paths:
      #- 'src/locales/en-US/grafana-synthetic-monitoring-app.json'
    branches:
      - hackathon/i18n-all-the-things

jobs:
  upload-sources-to-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      - name: Extract keys
        run: yarn i18n:extract

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          create_pull_request: false
          config: '.config-i18n/crowdin.yml'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
