name: Crowdin Download Action

on:
  workflow_dispatch:
  push:
    # paths:
    #  - 'src/locales/en-US/grafana-synthetic-monitoring-app.json'
    branches:
      - hackathon/i18n-all-the-things

jobs:
  download-sources-from-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin pull
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          create_pull_request: false
          push_translations: false
          config: '.i18n-tooling/crowdin.yml'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
