name: Add main bundle size

on:
  push:
    branches:
      - main

permissions:
  contents: none
  packages: none

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Make artifacts folder
        run: mkdir artifacts

      - name: Build frontend
        run: yarn build --json=artifacts/mainBundleSize.json --no-devtool

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mainBundleSize
          path: ./artifacts/mainBundleSize.json
          overwrite: true
