name: Publish to Grafana.com
run-name: 'Publish to grafana.com'

on:
  push:
    branches:
      - fix-gha-publish-plugin

jobs:
  publish-to-grafana-com:
    name: Publish to grafana.com
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get signing token from Vault
        uses: grafana/shared-workflows/actions/get-vault-secrets@75804962c1ba608148988c1e2dc35fbb0ee21746
        with:
          common_secrets: |
            GRAFANA_ACCESS_POLICY_TOKEN=plugins/sign-plugin-access-policy-token:token

      - name: Get plugin version
        id: get-version
        run: |
          VERSION=$(grep version package.json | cut -d':' -f2 | tr -d "\"', \r")
          echo "plugin_version=${VERSION}" >> "${GITHUB_OUTPUT}"
          echo "Plugin version: ${VERSION}"

      - name: Publish plugin to grafana.com
        env:
          GRAFANA_API_KEY: ${{ env.GRAFANA_ACCESS_POLICY_TOKEN }}
        run: |
          echo "Publishing plugin to grafana.com with version: ${{ steps.get-version.outputs.plugin_version }}"
          ./scripts/publish-gcom.sh 