name: On pushing to main

on:
  push:
    branches:
      - main

jobs:
  publish-techdocs:
    name: Publish TechDocs
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/call_publish-techdocs.yml

  release-please:
    name: Release Please
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/call_release-please.yml

  main-bundle-size:
    name: Generate Main Bundle Size
    permissions:
      contents: read
      attestations: write
    uses: ./.github/workflows/call_main-bundle-size.yml

  deploy-to-dev:
    name: Deploy to Dev
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/call_deploy-plugin.yml
    with:
      environment: 'dev'
      autoMerge: 'true'
