name: Temp - Publish to Ops Catalog

on:
  push:
    branches:
      - migrate-plugin-cdn

jobs:
  build-and-publish-ops:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Build Environment
        uses: ./.github/actions/setup-env

      - name: Get tokens from Vault
        uses: grafana/shared-workflows/actions/get-vault-secrets@75804962c1ba608148988c1e2dc35fbb0ee21746
        with:
          common_secrets: |
            GRAFANA_ACCESS_POLICY_TOKEN=plugins/sign-plugin-access-policy-token:token
            GCOM_PUBLISH_TOKEN_OPS=plugins/gcom-publish-token:ops

      - name: Build, sign and package plugin
        env:
          GRAFANA_ACCESS_POLICY_TOKEN: ${{ env.GRAFANA_ACCESS_POLICY_TOKEN }}
        run: |
          make build sign package

      - name: Publish plugin to ops catalog
        env:
          GCOM_PUBLISH_TOKEN: ${{ env.GCOM_PUBLISH_TOKEN_OPS }}
        run: |
          echo "Publishing plugin to ops catalog"
          ./scripts/publish-gcom-ops.sh
