name: Validate pull request

on:
  pull_request:

permissions: {}

jobs:
  # Main CI/CD workflow (shared workflow handles: lint, test, build, typecheck)
  ci:
    name: CI
    # Documentation: https://enghub.grafana-ops.net/docs/default/component/grafana-plugins-platform/plugins-ci-github-actions/010-plugins-ci-github-actions
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@ci-cd-workflows/v11.1.0
    permissions:
      contents: read # write is only needed if we publish docs to the website.
      id-token: write
    with:
      branch: ${{ github.ref }}

      # Add git SHA to plugin version as suffix for CD builds
      plugin-version-suffix: ${{ github.event.pull_request.head.sha }}

      # Other CI inputs, see https://github.com/grafana/plugin-ci-workflows/blob/main/.github/workflows/ci.yml

      # Node.js version to use
      node-version: 22

      npm-registry-auth: true

      run-playwright: true
      playwright-docker-compose-file: tests/playwright/docker-compose.yml
      playwright-secrets: |
        SM_E2E_API_HOST=e2e:api_host
        SM_E2E_ACCESS_TOKEN=e2e:access_token
        SM_E2E_RESULTS_API_URL=e2e:results_api_url
        SM_E2E_RESULTS_STACK_ID=e2e:results_stack_id
        SM_E2E_RESULTS_API_TOKEN=e2e:results_api_token
        SM_E2E_FARO_COLLECTOR_URL=e2e:faro_collector_url
